#!/bin/sh

git submodule init
git submodule update

android update project --path formidable-client 
android update project --path instrumentation-test 
android update project --path dependencies/touchdb/TouchDB-Android
android update project --path dependencies/touchdb/TouchDB-Android-Ektorp
android update project --path dependencies/TouchDB-Android-Lucene

